user:
  tag:
    name: Отмечать в чате
    description: Определяет будет ли отображаться ваш никнейм в чате при использовании алгоритмов случайного подбора пользователя
    default: True
  whisper:
    name: Личные сообщения
    description: Может ли бот отправлять вам личные сообщение по какому-либо поводу
    default: True
  calling:
    name: Обращение
    description: Как бот будет обращаться к вам в чате
    default: nickname
channel:
  reply:
    name: Отвечать с выделением сообщения
    description: Вместо того, чтобы вписывать имя пользователя в ответ на команды, бот будет отмечать сообщения с командой
    default: False
  kd:
    name: Общий кд использования бота
    description: Задержка для использования команд в целом
    default: 1
  role:
    name: Минимальный уровень привелегий для доступа к админ-панели
    description: Все пользователи, которые выше по списку относительно выбранного уровня привелегий, будут допущены в админ-панель
    default: super_user
    list:
      - super_user
      - moderator
      - vip
  links:
    name: Удалять ссылки
    description: Будут удаляться все ссылки, которые попадут в вывод бота
    default: False
commands:
  help:
    description: Выводит ссылку на страницу с командами
    result: "Список всех команд: {ссылка на команды}"
  курс:
    description: Выводит текущий курс доллара, евро, йены и гривны в рубли, можно также перевести из из одной валюты в другую, например (!курс usd-eur 4000, !курс usd-uah 15)
    result: "{пользователь}, Курс валют на {время сейчас}: USD = {курс доллара} RUB | EUR = {курс евро}
                    RUB | BTC = {курс биткоина} RUB | UAH = {курс гривны} RUB"
  перевод:
    description: Принимает слово или предложение, возвращает то же слово или предложение, но переведённое на русский язык, можно указать вводимый язык и в какой язык нужно перевести
    result: "{перевод}"
  статистика:
    description: Возвращает статистику пользователя, использовавшего команду, если команда введена с параметром, то бот выдаст статистику на пользователя по параметру
    result: "{пользователь} написал всего сообщений: {кол-во сообщений}, проведено времени в чате: {кол-во времени}"
  анекдот:
    description: Выводит случайный анекдот
    result: "{анекдот}"
  цитата:
    description: Выводит случайную цитату
    result: "{цитата}"
  рецепт:
    description: Выводит случайный рецепт с ингредиентами и способом приготовления
    result: "{рецепт}"

